//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace satıs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kategoriler
    {
        public int katid { get; set; }
        public string katad { get; set; }
    }
}
