//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace satıs.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class karaca_teknolojiEntities3 : DbContext
    {
        public karaca_teknolojiEntities3()
            : base("name=karaca_teknolojiEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kategoriler> kategorilers { get; set; }
        public virtual DbSet<kullanıcılar> kullanıcılar { get; set; }
        public virtual DbSet<satıslar> satıslar { get; set; }
        public virtual DbSet<ürünler> ürünler { get; set; }

        internal void SignInAsync(string p1, string p2)
        {
            throw new NotImplementedException();
        }
    }
}
