//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace satıs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class satıslar
    {
        public int satisid { get; set; }
        public Nullable<int> ürünid { get; set; }
        public Nullable<int> katid { get; set; }
        public string adsoyad { get; set; }
        public string adres { get; set; }
        public string telefon { get; set; }
        public Nullable<double> tutar { get; set; }
        public Nullable<System.DateTime> islemzamanı { get; set; }
    }
}
