//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace satıs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ürünler
    {
        public int ürünid { get; set; }
        public Nullable<int> katid { get; set; }
        public string ürünbarkod { get; set; }
        public string ürünfoto { get; set; }
        public string ürünad { get; set; }
        public string ürünozellik { get; set; }
        public Nullable<double> ürünfiyat { get; set; }
    }
}
